from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException, Request, Response, status
from sqlalchemy import select
from sqlalchemy.orm import Session, selectinload

from app.audit import record_audit
from app.database import get_db
from app.deps import require_analyst, require_viewer
from app.models import Entity, Report, User
from app.schemas import ReportCreate, ReportOut

router = APIRouter(prefix="/reports", tags=["reports"])


def report_or_404(db: Session, report_id: str) -> Report:
    report = db.scalar(select(Report).options(selectinload(Report.entities)).where(Report.id == report_id))
    if report is None:
        raise HTTPException(status_code=404, detail="Report not found")
    return report


@router.get("", response_model=list[ReportOut])
def list_reports(_: User = Depends(require_viewer), db: Session = Depends(get_db)) -> list[Report]:
    return list(
        db.scalars(
            select(Report).options(selectinload(Report.entities)).order_by(Report.updated_at.desc())
        ).all()
    )


@router.post("", response_model=ReportOut, status_code=status.HTTP_201_CREATED)
def create_report(
    payload: ReportCreate,
    request: Request,
    actor: User = Depends(require_analyst),
    db: Session = Depends(get_db),
) -> Report:
    entities = (
        list(db.scalars(select(Entity).where(Entity.id.in_(payload.entity_ids))).all())
        if payload.entity_ids
        else []
    )
    report = Report(
        title=payload.title,
        executive_summary=payload.executive_summary,
        assessment=payload.assessment,
        confidence=payload.confidence,
        created_by=actor.id,
        entities=entities,
    )
    db.add(report)
    db.flush()
    record_audit(db, "report.create", "report", report.id, actor, request, {"entities": len(entities)})
    db.commit()
    return report_or_404(db, report.id)


@router.get("/{report_id}/markdown")
def report_markdown(
    report_id: str,
    _: User = Depends(require_viewer),
    db: Session = Depends(get_db),
) -> Response:
    report = report_or_404(db, report_id)
    entities = (
        "\n".join(
            f"- `{entity.type}` — `{entity.value}` — risk {entity.risk_score}/100"
            for entity in report.entities
        )
        or "- None linked"
    )
    markdown = f"""# {report.title}

**Confidence:** {report.confidence}/100

## Executive summary

{report.executive_summary}

## Assessment

{report.assessment}

## Linked intelligence

{entities}

---

Generated by SignalGraph v1.0.0.
"""
    return Response(
        markdown,
        media_type="text/markdown",
        headers={"Content-Disposition": f'attachment; filename="report-{report.id}.md"'},
    )
